name: Security Issues

on:
  - push

jobs:

  playground:
    name: Condition
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v2

      - name: Create fake input
        run: >
          cat << EOF
          {
            "reports" : {
              "net.bytebuddy:byte-buddy-agent:jar:1.14.8:test" : {
                "coordinates" : "pkg:maven/net.bytebuddy/byte-buddy-agent@1.14.8",
                "reference" : "https://ossindex.sonatype.org/component/pkg:maven/net.bytebuddy/byte-buddy-agent@1.14.8?utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1"
              }
            },
            "vulnerable" : {
              "fr.turri:aXMLRPC:jar:1.13.0:compile" : {
                "coordinates" : "pkg:maven/fr.turri/aXMLRPC@1.13.0",
                "description" : "Lightweight Java XML-RPC working also on Android.",
                "reference" : "https://ossindex.sonatype.org/component/pkg:maven/fr.turri/aXMLRPC@1.13.0?utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1",
                "vulnerabilities" : [ {
                  "id" : "CVE-2020-36641",
                  "displayName" : "CVE-2020-36641",
                  "title" : "[CVE-2020-36641] CWE-611: Improper Restriction of XML External Entity Reference ('XXE')",
                  "description" : "A vulnerability classified as problematic was found in gturri aXMLRPC up to 1.12.0. This vulnerability affects the function ResponseParser of the file src/main/java/de/timroes/axmlrpc/ResponseParser.java. The manipulation leads to xml external entity reference. Upgrading to version 1.12.1 is able to address this issue. The name of the patch is ad6615b3ec41353e614f6ea5fdd5b046442a832b. It is recommended to upgrade the affected component. VDB-217450 is the identifier assigned to this vulnerability.\n\nSonatype's research suggests that this CVE's details differ from those defined at NVD. See https://ossindex.sonatype.org/vulnerability/CVE-2020-36641 for details",
                  "cvssScore" : 9.8,
                  "cvssVector" : "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                  "cwe" : "CWE-611",
                  "cve" : "CVE-2020-36641",
                  "reference" : "https://ossindex.sonatype.org/vulnerability/CVE-2020-36641?component-type=maven&component-name=fr.turri%2FaXMLRPC&utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1",
                  "externalReferences" : [ "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-36641", "https://www.tenable.com/cve/CVE-2020-36641" ]
                } ]
              }
            },
            "excludedVulnerabilities" : [ {
              "id" : "CVE-2023-4586",
              "displayName" : "CVE-2023-4586",
              "title" : "[CVE-2023-4586] CWE-300: Channel Accessible by Non-Endpoint ('Man-in-the-Middle')",
              "description" : "netty-handler - Improper Certificate Validation\n\nThe product does not adequately verify the identity of actors at both ends of a communication channel, or does not adequately ensure the integrity of the channel, in a way that allows the channel to be accessed or influenced by an actor that is not an endpoint.",
              "cvssScore" : 6.5,
              "cvssVector" : "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:L/A:N",
              "cwe" : "CWE-300",
              "cve" : "CVE-2023-4586",
              "reference" : "https://ossindex.sonatype.org/vulnerability/CVE-2023-4586?component-type=maven&component-name=io.netty%2Fnetty-handler&utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1",
              "externalReferences" : [ "https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm-java.lang.String-", "https://github.com/netty/netty/issues/8537", "https://github.com/netty/netty/issues/9930", "https://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html#newHandler-io.netty.buffer.ByteBufAllocator-java.util.concurrent.Executor-" ]
            } ]
            EOF > report.json

      - name: echo
        run: echo report.json
