name: Security Issues

on:
  - push

jobs:

  playground:
    name: Report Security Issues
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v2

      - name: Create fake input
        run:  cat maven-output.json > report.json

      - name: echo
        run: cat report.json

      - name: Process Security Issues
        uses: exasol/python-toolbox/.github/actions/security-issues@feature/security-issues-action
        with:
          command: "cat maven-output.json"
